addons:
  apt:
    packages:
     - libgsl0-dev
     - xvfb

sudo: false

language: r
before_install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - R -q -e 'install.packages("BiocManager"); BiocManager::install(c("graph","RDRToolbox","Rgraphviz"), update=FALSE, ask=FALSE)'

  
cache: packages
warnings_are_errors: false

r:
 - release
 - devel

