addons:
  apt:
    packages:
     - xvfb

sudo: false

language: r
before_install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  
cache: packages

r:
 - release
 - devel

