name: R-CMD-check (manual, safe)

on:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      _R_CHECK_FORCE_SUGGESTS_: "false"   # don't force-install Suggests (e.g. loon/qqtest)
      TZ: UTC
      RGL_USE_NULL: "true"                # generic headless hint

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: local::.
          needs: check

      # Run build + check inside a virtual X display so tcltk/loon won't choke
      - name: Run R CMD check under Xvfb
        uses: GabrielBB/xvfb-action@v1
        with:
          run: |
            R CMD build .
            PKG_TAR=$(ls -1t *.tar.gz | head -n 1)
            R CMD check "${PKG_TAR}" --no-manual --as-cran

      - name: Upload check results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Rcheck-results
          path: |
            **/*.Rcheck/**/*

