name: R-CMD-check

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  R-CMD-check:
    name: ${{ matrix.config.os }} (R ${{ matrix.config.r }}, Suggests except loon)
    runs-on: ${{ matrix.config.os }}

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macos-latest,   r: 'release'}
          - {os: windows-latest, r: 'release'}
          - {os: ubuntu-latest,  r: 'devel'}
          - {os: ubuntu-latest,  r: 'release'}
          - {os: ubuntu-latest,  r: 'oldrel-1'}

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}

      - uses: r-lib/actions/setup-pandoc@v2

      - name: Install dependencies (skip loon)
        run: |
          install.packages("remotes")
          remotes::install_deps(dependencies = TRUE)
          pkgs <- setdiff(
            tools::package_dependencies("zenplots", db = available.packages(), which = "Suggests")[[1]],
            "loon"
          )
          if (length(pkgs)) install.packages(pkgs, repos = "https://cloud.r-project.org")

      - name: Check
        run: |
          options(crayon.enabled = TRUE)
          devtools::check(args = c("--no-manual", "--as-cran"), error_on = "warning")

  loon-test:
    name: Ubuntu loon test (non-blocking)
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'

      - name: Install all dependencies including loon
        run: |
          install.packages("remotes")
          remotes::install_deps(dependencies = TRUE)
          install.packages("loon", repos = "https://cloud.r-project.org")

      - name: Check (with loon)
        run: |
          options(crayon.enabled = TRUE)
          devtools::check(args = c("--no-manual", "--as-cran"), error_on = "warning")

