name: R-CMD-check

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  check:
    name: ${{ matrix.os }} (R ${{ matrix.r }}, Suggests≠ loon/graph/Rgraphviz)
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        r:  [release]

    env:
      _R_CHECK_FORCE_SUGGESTS_: "false"
      NOT_CRAN: "true"
      R_KEEP_PKG_SOURCE: "yes"

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-pandoc@v2

      - name: Install required base tools
        run: |
          Rscript -e 'install.packages(c("remotes","devtools"), repos="https://cloud.r-project.org")'

      - name: Install Depends/Imports/LinkingTo explicitly (includes PairViz)
        run: |
          Rscript - <<'RS'
          d <- read.dcf("DESCRIPTION")
          get <- function(field) {
            if (!(field %in% colnames(d))) return(character(0))
            x <- trimws(gsub("\\(.*?\\)", "", unlist(strsplit(d[1, field], ","))))
            x[x != "R"]
          }
          pkgs <- unique(c(get("Depends"), get("Imports"), get("LinkingTo")))
          if (length(pkgs)) install.packages(pkgs, repos="https://cloud.r-project.org")
          RS

      - name: Install Suggests (CRAN only), skipping loon/graph/Rgraphviz
        run: |
          Rscript - <<'RS'
          d <- read.dcf("DESCRIPTION")
          get <- function(field) {
            if (!(field %in% colnames(d))) return(character(0))
            trimws(gsub("\\(.*?\\)", "", unlist(strsplit(d[1, field], ","))))
          }
          sugs <- get("Suggests")
          skip <- c("loon","graph","Rgraphviz")
          want <- setdiff(sugs, skip)
          if (length(want)) {
            ap <- available.packages(repos="https://cloud.r-project.org")
            cran_ok <- intersect(want, rownames(ap))
            not_cran <- setdiff(want, cran_ok)
            if (length(not_cran)) message("Skipping non-CRAN suggests: ", paste(not_cran, collapse=", "))
            if (length(cran_ok)) install.packages(cran_ok, repos="https://cloud.r-project.org")
          }
          RS

      - name: R CMD check
        run: |
          Rscript -e 'options(crayon.enabled=TRUE); devtools::check(args=c("--no-manual","--as-cran"), error_on="warning")'

